# -*- coding: utf-8 -*-
"""helloworld.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15HTCHqXnCNbUom2-IXRwDXDDhPCV97P5
"""

# HELLO WORLD Random Forest with PyTorch

import torch
from sklearn.ensemble import RandomForestClassifier

print("Hello World - Random Forest with PyTorch")

#Create simple dataset using PyTorch tensors
#Features
X = torch.tensor([[1,2],[2,3],[3,4],[5,6]], dtype=torch.float32)

# Labels (y)
y = torch.tensor([0,0,1,1])

# Convert tensors to numpy
X_np = X.numpy()
y_np = y.numpy()

#Create Random Forest model
model = RandomForestClassifier()

#Train model
model.fit(X_np, y_np)

#Test prediction
test = torch.tensor([[4,5]], dtype=torch.float32)

prediction = model.predict(test.numpy())

print("Prediction:", prediction)